const { createCanvas, loadImage } = require('@napi-rs/canvas');

exports.handler = async (event, context) => {
    try {
            const query = event.queryStringParameters || {};
                    const username = query.username || 'User';
                            const level = query.level || '1';
                                    const rank = query.rank || '1';
                                            const xp = parseInt(query.xp || '50', 10);
                                                    const maxXP = parseInt(query.maxXP || '100', 10);
                                                            const avatarUrl = query.avatar || 'https://cdn.discordapp.com/embed/avatars/0.png';

                                                                    const canvas = createCanvas(934, 282);
                                                                            const ctx = canvas.getContext('2d');

                                                                                    // خلفية البطاقة
                                                                                            ctx.fillStyle = '#23272a';
                                                                                                    ctx.fillRect(0, 0, canvas.width, canvas.height);

                                                                                                            // اسم المستخدم
                                                                                                                    ctx.fillStyle = '#ffffff';
                                                                                                                            ctx.font = 'bold 36px sans-serif';
                                                                                                                                    ctx.fillText(username, 270, 100);

                                                                                                                                            // المستوى والترتيب
                                                                                                                                                    ctx.font = '24px sans-serif';
                                                                                                                                                            ctx.fillStyle = '#7289da';
                                                                                                                                                                    ctx.fillText(`LEVEL: ${level}`, 700, 80);
                                                                                                                                                                            ctx.fillText(`RANK: #${rank}`, 700, 120);

                                                                                                                                                                                    // خلفية شريط الخبرة
                                                                                                                                                                                            ctx.fillStyle = '#484b5e';
                                                                                                                                                                                                    ctx.beginPath();
                                                                                                                                                                                                            ctx.roundRect(270, 160, 600, 30, 15);
                                                                                                                                                                                                                    ctx.fill();

                                                                                                                                                                                                                            // شريط التقدم الفعلي
                                                                                                                                                                                                                                    const progressWidth = Math.min(Math.max((xp / maxXP) * 600, 30), 600);
                                                                                                                                                                                                                                            ctx.fillStyle = '#f04747';
                                                                                                                                                                                                                                                    ctx.beginPath();
                                                                                                                                                                                                                                                            ctx.roundRect(270, 160, progressWidth, 30, 15);
                                                                                                                                                                                                                                                                    ctx.fill();

                                                                                                                                                                                                                                                                            // صورة الأفاتار الدائرية
                                                                                                                                                                                                                                                                                    try {
                                                                                                                                                                                                                                                                                                const avatar = await loadImage(avatarUrl);
                                                                                                                                                                                                                                                                                                            ctx.save();
                                                                                                                                                                                                                                                                                                                        ctx.beginPath();
                                                                                                                                                                                                                                                                                                                                    ctx.arc(135, 141, 80, 0, Math.PI * 2, true);
                                                                                                                                                                                                                                                                                                                                                ctx.closePath();
                                                                                                                                                                                                                                                                                                                                                            ctx.clip();
                                                                                                                                                                                                                                                                                                                                                                        ctx.drawImage(avatar, 55, 61, 160, 160);
                                                                                                                                                                                                                                                                                                                                                                                    ctx.restore();
                                                                                                                                                                                                                                                                                                                                                                                            } catch (avatarError) {
                                                                                                                                                                                                                                                                                                                                                                                                        // تخطي رسم الأفاتار في حال فشل تحميل الرابط لتجنب تعطل الدالة
                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                        const buffer = canvas.toBuffer('image/png');

                                                                                                                                                                                                                                                                                                                                                                                                                                return {
                                                                                                                                                                                                                                                                                                                                                                                                                                            statusCode: 200,
                                                                                                                                                                                                                                                                                                                                                                                                                                                        headers: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'Content-Type': 'image/png',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                body: buffer.toString('base64'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            isBase64Encoded: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            statusCode: 500,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        body: JSON.stringify({ error: error.message }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    